### ISSUE TITLE
🔧 App Rework

### ISSUE THREAD

**Issue by fedetomassini** [fedetomassini/todolist-app#1]
## Tasks
- [ ] Review the existing code structure.
- [ ] Refactor components to improve readability and maintainability.
- [ ] Redesign the UI for better usability and responsiveness.

**Comment by fedetomassini** [comment]
~ *App features will be ingrated to Nivo.* **(Q3)**

**Comment by fedetomassini** [comment]
App deprecated, will be integrated to Nivo.
